### ISSUE TITLE
Core dump with intervention=1

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#17] opened 2020-07-04 23:06 UTC
https://github.com/kassonlab/covid19-epi/blob/254de2cf3a2b912d1bef3d16a1130fe162652abe/covid19.c#L2078

Ic, Ih, Iw is never initialized will be null causing core dump

**Comment by peterkasson** [comment] 2020-07-05 02:04
Thank you; this was introduced at some point after May 7, it appears.  Will fix.

**Comment by peterkasson** [comment] 2020-07-05 03:01
This was broken in a0e69abadb8a3759807d42af00eba38efcf21de9.
Should be fixed in 71bb6c8aa5dec53d32d38fe576b9795d67edc8b3 (inter1 now runs for me, checking regression).

**Comment by peterkasson** [comment] 2020-07-14 01:57
Since we've reproduced and fixed this bug, marking the issue closed.  If it's not fixed for you, please comment, and we'll reopen.

**Closed by peterkasson** 2020-07-14 01:57 UTC
